import Head from "next/head";
import { HiOutlineDotsCircleHorizontal } from "react-icons/hi";
import { AiOutlineSound } from "react-icons/ai";
export default function Task() {
  return (
    <>
      <Head>
        <title>Task 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex h-screen overflow-hidden">
        <video
          src="/vidios/god.mp4"
          loop
          controls
          autoPlay
          muted
          className="absolute z-0 h-fit w-fit"
        />
        <div className="text-black z-10 ml-[10px]">
          <div className="mt-[30px] flex justify-between w-screen  ">
            <div className="flex justify-center items-center gap-2">
              <div className="h-[20px] w-[20px] bg-[#3d3d3d] rounded-full flex justify-center items-center text-[10px] text-white">
                Nk
              </div>
              <div className="font-Poppins font-normal leading-[18px] tracking-[0.0015em] text-[12px] text-[#FFFEFE]">
                Cakes & Cheese
              </div>
              <button className="py-2 px-4 font-Poppins font-normal bg-[#2c3033] rounded-[32px] text-[12px] text-[#FFFEFE]">
                Follow
              </button>
            </div>
            <div className="flex justify-center items-center gap-2 mr-[30px]">
              <HiOutlineDotsCircleHorizontal className="text-white h-6 w-6" />
              <AiOutlineSound className="text-white h-6 w-6" />
            </div>
          </div>
          <div className=" mt-[10px] font-Poppins font-normal leading-[18px] tracking-[0.004em] text-[12px] text-[#FFFEFE]">
            Get your fresh birthday cake today
          </div>
        </div>
      </div>
    </>
  );
}
