import VidSlider from "@/components/pages/task2/Slider";
import Head from "next/head";
import React from "react";

export default function Task() {
  return (
    <>
      <Head>
        <title>Task 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VidSlider />
    </>
  );
}
